-- Transfer census data from temp table to final table
-- This script should be run after 02-load-census-data.sh has created the temp table

-- Delete existing data and transfer all census data
DELETE FROM cim_census.census_geo;

INSERT INTO cim_census.census_geo (
    SEZ2011, geometry, Shape_Area, CODREG, REGIONE, CODPRO, PROVINCIA,
    CODCOM, COMUNE, PROCOM, NSEZ, ACE, CODLOC, CODASC,
    P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16, P17, P18, P19, P20,
    P21, P22, P23, P24, P25, P26, P27, P28, P29, P30, P31, P32, P33, P34, P35, P36, P37, P38, P39, P40,
    P41, P42, P43, P44, P45, P46, P47, P48, P49, P50, P51, P52, P53, P54, P55, P56, P57, P58, P59, P60,
    P61, P62, P64, P65, P66, P128, P129, P130, P131, P132, P135, P136, P137, P138, P139, P140,
    ST1, ST2, ST3, ST4, ST5, ST6, ST7, ST8, ST9, ST10, ST11, ST12, ST13, ST14, ST15,
    A2, A3, A5, A6, A7, A44, A46, A47, A48,
    PF1, PF2, PF3, PF4, PF5, PF6, PF7, PF8, PF9,
    E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20,
    E21, E22, E23, E24, E25, E26, E27, E28, E29, E30, E31
)
SELECT 
    sez2011::bigint,
    CASE 
        WHEN ST_GeometryType(geometry) = 'ST_Polygon' THEN ST_Multi(geometry)
        ELSE geometry
    END,
    shape_area,
    codreg, regione, codpro, provincia, codcom, comune, procom, nsez, ace, codloc, codasc,
    -- Population attributes P1-P140
    CASE WHEN p1::text ~ '^[0-9]+$' THEN p1::text::integer ELSE NULL END,
    CASE WHEN p2::text ~ '^[0-9]+$' THEN p2::text::integer ELSE NULL END,
    CASE WHEN p3::text ~ '^[0-9]+$' THEN p3::text::integer ELSE NULL END,
    CASE WHEN p4::text ~ '^[0-9]+$' THEN p4::text::integer ELSE NULL END,
    CASE WHEN p5::text ~ '^[0-9]+$' THEN p5::text::integer ELSE NULL END,
    CASE WHEN p6::text ~ '^[0-9]+$' THEN p6::text::integer ELSE NULL END,
    CASE WHEN p7::text ~ '^[0-9]+$' THEN p7::text::integer ELSE NULL END,
    CASE WHEN p8::text ~ '^[0-9]+$' THEN p8::text::integer ELSE NULL END,
    CASE WHEN p9::text ~ '^[0-9]+$' THEN p9::text::integer ELSE NULL END,
    CASE WHEN p10::text ~ '^[0-9]+$' THEN p10::text::integer ELSE NULL END,
    CASE WHEN p11::text ~ '^[0-9]+$' THEN p11::text::integer ELSE NULL END,
    CASE WHEN p12::text ~ '^[0-9]+$' THEN p12::text::integer ELSE NULL END,
    CASE WHEN p13::text ~ '^[0-9]+$' THEN p13::text::integer ELSE NULL END,
    CASE WHEN p14::text ~ '^[0-9]+$' THEN p14::text::integer ELSE NULL END,
    CASE WHEN p15::text ~ '^[0-9]+$' THEN p15::text::integer ELSE NULL END,
    CASE WHEN p16::text ~ '^[0-9]+$' THEN p16::text::integer ELSE NULL END,
    CASE WHEN p17::text ~ '^[0-9]+$' THEN p17::text::integer ELSE NULL END,
    CASE WHEN p18::text ~ '^[0-9]+$' THEN p18::text::integer ELSE NULL END,
    CASE WHEN p19::text ~ '^[0-9]+$' THEN p19::text::integer ELSE NULL END,
    CASE WHEN p20::text ~ '^[0-9]+$' THEN p20::text::integer ELSE NULL END,
    CASE WHEN p21::text ~ '^[0-9]+$' THEN p21::text::integer ELSE NULL END,
    CASE WHEN p22::text ~ '^[0-9]+$' THEN p22::text::integer ELSE NULL END,
    CASE WHEN p23::text ~ '^[0-9]+$' THEN p23::text::integer ELSE NULL END,
    CASE WHEN p24::text ~ '^[0-9]+$' THEN p24::text::integer ELSE NULL END,
    CASE WHEN p25::text ~ '^[0-9]+$' THEN p25::text::integer ELSE NULL END,
    CASE WHEN p26::text ~ '^[0-9]+$' THEN p26::text::integer ELSE NULL END,
    CASE WHEN p27::text ~ '^[0-9]+$' THEN p27::text::integer ELSE NULL END,
    CASE WHEN p28::text ~ '^[0-9]+$' THEN p28::text::integer ELSE NULL END,
    CASE WHEN p29::text ~ '^[0-9]+$' THEN p29::text::integer ELSE NULL END,
    CASE WHEN p30::text ~ '^[0-9]+$' THEN p30::text::integer ELSE NULL END,
    CASE WHEN p31::text ~ '^[0-9]+$' THEN p31::text::integer ELSE NULL END,
    CASE WHEN p32::text ~ '^[0-9]+$' THEN p32::text::integer ELSE NULL END,
    CASE WHEN p33::text ~ '^[0-9]+$' THEN p33::text::integer ELSE NULL END,
    CASE WHEN p34::text ~ '^[0-9]+$' THEN p34::text::integer ELSE NULL END,
    CASE WHEN p35::text ~ '^[0-9]+$' THEN p35::text::integer ELSE NULL END,
    CASE WHEN p36::text ~ '^[0-9]+$' THEN p36::text::integer ELSE NULL END,
    CASE WHEN p37::text ~ '^[0-9]+$' THEN p37::text::integer ELSE NULL END,
    CASE WHEN p38::text ~ '^[0-9]+$' THEN p38::text::integer ELSE NULL END,
    CASE WHEN p39::text ~ '^[0-9]+$' THEN p39::text::integer ELSE NULL END,
    CASE WHEN p40::text ~ '^[0-9]+$' THEN p40::text::integer ELSE NULL END,
    CASE WHEN p41::text ~ '^[0-9]+$' THEN p41::text::integer ELSE NULL END,
    CASE WHEN p42::text ~ '^[0-9]+$' THEN p42::text::integer ELSE NULL END,
    CASE WHEN p43::text ~ '^[0-9]+$' THEN p43::text::integer ELSE NULL END,
    CASE WHEN p44::text ~ '^[0-9]+$' THEN p44::text::integer ELSE NULL END,
    CASE WHEN p45::text ~ '^[0-9]+$' THEN p45::text::integer ELSE NULL END,
    CASE WHEN p46::text ~ '^[0-9]+$' THEN p46::text::integer ELSE NULL END,
    CASE WHEN p47::text ~ '^[0-9]+$' THEN p47::text::integer ELSE NULL END,
    CASE WHEN p48::text ~ '^[0-9]+$' THEN p48::text::integer ELSE NULL END,
    CASE WHEN p49::text ~ '^[0-9]+$' THEN p49::text::integer ELSE NULL END,
    CASE WHEN p50::text ~ '^[0-9]+$' THEN p50::text::integer ELSE NULL END,
    CASE WHEN p51::text ~ '^[0-9]+$' THEN p51::text::integer ELSE NULL END,
    CASE WHEN p52::text ~ '^[0-9]+$' THEN p52::text::integer ELSE NULL END,
    CASE WHEN p53::text ~ '^[0-9]+$' THEN p53::text::integer ELSE NULL END,
    CASE WHEN p54::text ~ '^[0-9]+$' THEN p54::text::integer ELSE NULL END,
    CASE WHEN p55::text ~ '^[0-9]+$' THEN p55::text::integer ELSE NULL END,
    CASE WHEN p56::text ~ '^[0-9]+$' THEN p56::text::integer ELSE NULL END,
    CASE WHEN p57::text ~ '^[0-9]+$' THEN p57::text::integer ELSE NULL END,
    CASE WHEN p58::text ~ '^[0-9]+$' THEN p58::text::integer ELSE NULL END,
    CASE WHEN p59::text ~ '^[0-9]+$' THEN p59::text::integer ELSE NULL END,
    CASE WHEN p60::text ~ '^[0-9]+$' THEN p60::text::integer ELSE NULL END,
    CASE WHEN p61::text ~ '^[0-9]+$' THEN p61::text::integer ELSE NULL END,
    CASE WHEN p62::text ~ '^[0-9]+$' THEN p62::text::integer ELSE NULL END,
    CASE WHEN p64::text ~ '^[0-9]+$' THEN p64::text::integer ELSE NULL END,
    CASE WHEN p65::text ~ '^[0-9]+$' THEN p65::text::integer ELSE NULL END,
    CASE WHEN p66::text ~ '^[0-9]+$' THEN p66::text::integer ELSE NULL END,
    CASE WHEN p128::text ~ '^[0-9]+$' THEN p128::text::integer ELSE NULL END,
    CASE WHEN p129::text ~ '^[0-9]+$' THEN p129::text::integer ELSE NULL END,
    CASE WHEN p130::text ~ '^[0-9]+$' THEN p130::text::integer ELSE NULL END,
    CASE WHEN p131::text ~ '^[0-9]+$' THEN p131::text::integer ELSE NULL END,
    CASE WHEN p132::text ~ '^[0-9]+$' THEN p132::text::integer ELSE NULL END,
    CASE WHEN p135::text ~ '^[0-9]+$' THEN p135::text::integer ELSE NULL END,
    CASE WHEN p136::text ~ '^[0-9]+$' THEN p136::text::integer ELSE NULL END,
    CASE WHEN p137::text ~ '^[0-9]+$' THEN p137::text::integer ELSE NULL END,
    CASE WHEN p138::text ~ '^[0-9]+$' THEN p138::text::integer ELSE NULL END,
    CASE WHEN p139::text ~ '^[0-9]+$' THEN p139::text::integer ELSE NULL END,
    CASE WHEN p140::text ~ '^[0-9]+$' THEN p140::text::integer ELSE NULL END,
    -- Housing statistics ST1-ST15
    CASE WHEN st1::text ~ '^[0-9]+$' THEN st1::text::integer ELSE NULL END,
    CASE WHEN st2::text ~ '^[0-9]+$' THEN st2::text::integer ELSE NULL END,
    CASE WHEN st3::text ~ '^[0-9]+$' THEN st3::text::integer ELSE NULL END,
    CASE WHEN st4::text ~ '^[0-9]+$' THEN st4::text::integer ELSE NULL END,
    CASE WHEN st5::text ~ '^[0-9]+$' THEN st5::text::integer ELSE NULL END,
    CASE WHEN st6::text ~ '^[0-9]+$' THEN st6::text::integer ELSE NULL END,
    CASE WHEN st7::text ~ '^[0-9]+$' THEN st7::text::integer ELSE NULL END,
    CASE WHEN st8::text ~ '^[0-9]+$' THEN st8::text::integer ELSE NULL END,
    CASE WHEN st9::text ~ '^[0-9]+$' THEN st9::text::integer ELSE NULL END,
    CASE WHEN st10::text ~ '^[0-9]+$' THEN st10::text::integer ELSE NULL END,
    CASE WHEN st11::text ~ '^[0-9]+$' THEN st11::text::integer ELSE NULL END,
    CASE WHEN st12::text ~ '^[0-9]+$' THEN st12::text::integer ELSE NULL END,
    CASE WHEN st13::text ~ '^[0-9]+$' THEN st13::text::integer ELSE NULL END,
    CASE WHEN st14::text ~ '^[0-9]+$' THEN st14::text::integer ELSE NULL END,
    CASE WHEN st15::text ~ '^[0-9]+$' THEN st15::text::integer ELSE NULL END,
    -- Building age attributes A2-A48
    CASE WHEN a2::text ~ '^[0-9]+$' THEN a2::text::integer ELSE NULL END,
    CASE WHEN a3::text ~ '^[0-9]+$' THEN a3::text::integer ELSE NULL END,
    CASE WHEN a5::text ~ '^[0-9]+$' THEN a5::text::integer ELSE NULL END,
    CASE WHEN a6::text ~ '^[0-9]+$' THEN a6::text::integer ELSE NULL END,
    CASE WHEN a7::text ~ '^[0-9]+$' THEN a7::text::integer ELSE NULL END,
    CASE WHEN a44::text ~ '^[0-9]+$' THEN a44::text::integer ELSE NULL END,
    CASE WHEN a46::text ~ '^[0-9]+$' THEN a46::text::integer ELSE NULL END,
    CASE WHEN a47::text ~ '^[0-9]+$' THEN a47::text::integer ELSE NULL END,
    CASE WHEN a48::text ~ '^[0-9]+$' THEN a48::text::integer ELSE NULL END,
    -- Family attributes PF1-PF9
    CASE WHEN pf1::text ~ '^[0-9]+$' THEN pf1::text::integer ELSE NULL END,
    CASE WHEN pf2::text ~ '^[0-9]+$' THEN pf2::text::integer ELSE NULL END,
    CASE WHEN pf3::text ~ '^[0-9]+$' THEN pf3::text::integer ELSE NULL END,
    CASE WHEN pf4::text ~ '^[0-9]+$' THEN pf4::text::integer ELSE NULL END,
    CASE WHEN pf5::text ~ '^[0-9]+$' THEN pf5::text::integer ELSE NULL END,
    CASE WHEN pf6::text ~ '^[0-9]+$' THEN pf6::text::integer ELSE NULL END,
    CASE WHEN pf7::text ~ '^[0-9]+$' THEN pf7::text::integer ELSE NULL END,
    CASE WHEN pf8::text ~ '^[0-9]+$' THEN pf8::text::integer ELSE NULL END,
    CASE WHEN pf9::text ~ '^[0-9]+$' THEN pf9::text::integer ELSE NULL END,
    -- Building period attributes E1-E31
    CASE WHEN e1::text ~ '^[0-9]+$' THEN e1::text::integer ELSE NULL END,
    CASE WHEN e2::text ~ '^[0-9]+$' THEN e2::text::integer ELSE NULL END,
    CASE WHEN e3::text ~ '^[0-9]+$' THEN e3::text::integer ELSE NULL END,
    CASE WHEN e4::text ~ '^[0-9]+$' THEN e4::text::integer ELSE NULL END,
    CASE WHEN e5::text ~ '^[0-9]+$' THEN e5::text::integer ELSE NULL END,
    CASE WHEN e6::text ~ '^[0-9]+$' THEN e6::text::integer ELSE NULL END,
    CASE WHEN e7::text ~ '^[0-9]+$' THEN e7::text::integer ELSE NULL END,
    CASE WHEN e8::text ~ '^[0-9]+$' THEN e8::text::integer ELSE NULL END,
    CASE WHEN e9::text ~ '^[0-9]+$' THEN e9::text::integer ELSE NULL END,
    CASE WHEN e10::text ~ '^[0-9]+$' THEN e10::text::integer ELSE NULL END,
    CASE WHEN e11::text ~ '^[0-9]+$' THEN e11::text::integer ELSE NULL END,
    CASE WHEN e12::text ~ '^[0-9]+$' THEN e12::text::integer ELSE NULL END,
    CASE WHEN e13::text ~ '^[0-9]+$' THEN e13::text::integer ELSE NULL END,
    CASE WHEN e14::text ~ '^[0-9]+$' THEN e14::text::integer ELSE NULL END,
    CASE WHEN e15::text ~ '^[0-9]+$' THEN e15::text::integer ELSE NULL END,
    CASE WHEN e16::text ~ '^[0-9]+$' THEN e16::text::integer ELSE NULL END,
    CASE WHEN e17::text ~ '^[0-9]+$' THEN e17::text::integer ELSE NULL END,
    CASE WHEN e18::text ~ '^[0-9]+$' THEN e18::text::integer ELSE NULL END,
    CASE WHEN e19::text ~ '^[0-9]+$' THEN e19::text::integer ELSE NULL END,
    CASE WHEN e20::text ~ '^[0-9]+$' THEN e20::text::integer ELSE NULL END,
    CASE WHEN e21::text ~ '^[0-9]+$' THEN e21::text::integer ELSE NULL END,
    CASE WHEN e22::text ~ '^[0-9]+$' THEN e22::text::integer ELSE NULL END,
    CASE WHEN e23::text ~ '^[0-9]+$' THEN e23::text::integer ELSE NULL END,
    CASE WHEN e24::text ~ '^[0-9]+$' THEN e24::text::integer ELSE NULL END,
    CASE WHEN e25::text ~ '^[0-9]+$' THEN e25::text::integer ELSE NULL END,
    CASE WHEN e26::text ~ '^[0-9]+$' THEN e26::text::integer ELSE NULL END,
    CASE WHEN e27::text ~ '^[0-9]+$' THEN e27::text::integer ELSE NULL END,
    CASE WHEN e28::text ~ '^[0-9]+$' THEN e28::text::integer ELSE NULL END,
    CASE WHEN e29::text ~ '^[0-9]+$' THEN e29::text::integer ELSE NULL END,
    CASE WHEN e30::text ~ '^[0-9]+$' THEN e30::text::integer ELSE NULL END,
    CASE WHEN e31::text ~ '^[0-9]+$' THEN e31::text::integer ELSE NULL END
FROM cim_census.census_geo_temp;

-- Create spatial indexes after data transfer
CREATE INDEX IF NOT EXISTS idx_census_geo_geometry ON cim_census.census_geo USING GIST(geometry);
CREATE INDEX IF NOT EXISTS idx_census_geo_sez2011 ON cim_census.census_geo(SEZ2011);
CREATE INDEX IF NOT EXISTS idx_census_geo_comune ON cim_census.census_geo(COMUNE);

-- Clean up temp table
DROP TABLE IF EXISTS cim_census.census_geo_temp;

-- Verify data transfer
SELECT 'Census data transfer completed' as status;
SELECT 'Total records: ' || COUNT(*) as record_count FROM cim_census.census_geo;
SELECT 'Total population: ' || SUM(P1) as total_population FROM cim_census.census_geo WHERE P1 IS NOT NULL;
