#Ontop JDBC + explicit mapping path
jdbc.url=jdbc:postgresql://localhost:15432/cim_wizard_integrated
jdbc.driver=org.postgresql.Driver
jdbc.user=cim_wizard_user
jdbc.password=cim_wizard_password
ontop.mappingFile=/mnt/Data_HDD/00products/CIM_wizard/semantic/ontop/citygml-bot-sosa-ssn-geosparql-time.obda
