version: '3.8'

services:
  # PostgreSQL with PostGIS
  postgres:
    image: postgis/postgis:15-3.3
    container_name: cim_integrated_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cim_wizard_integrated
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # CIM Wizard Integrated Application
  cim_wizard:
    build: .
    container_name: cim_integrated_app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/cim_wizard_integrated
      DEBUG: ${DEBUG:-False}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py
      - ./run.py:/app/run.py

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cim_integrated_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cimwizard.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  default:
    name: cim_integrated_network
    driver: bridge