# CIM Wizard PostGIS Database - Clean Setup for Manual Configuration
# This configuration creates a clean PostGIS database for manual setup
# No pgAdmin included - use local pgAdmin or QGIS for database management

services:
  db:
    # Use standard PostGIS image for better portability
    image: postgis/postgis:15-3.4
    container_name: cim_wizard_integrated
    restart: unless-stopped

    # Publish DB on host port 5433
    ports:
      - "5433:5432"

    # Mount raw data for access (no init scripts - manual setup)
    volumes:
      - ./rawdata:/rawdata:ro

    # Database configuration
    environment:
      POSTGRES_DB: cim_wizard_integrated
      POSTGRES_USER: cim_wizard_user
      POSTGRES_PASSWORD: cim_wizard_password
      PGDATA: /var/lib/postgresql/data/pgdata

    # Health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

    # Network configuration
    networks:
      - cim_network

networks:
  cim_network:
    name: cim_wizard_network
    driver: bridge