# CIM Wizard PostGIS Database - Portable Setup
# This configuration creates a PostGIS database with persistent data in cim_db folder
# Easy to move between servers by copying the docker-compose file and cim_db folder

services:
  db:
    # Use standard PostGIS image for better portability
    image: postgis/postgis:15-3.4
    container_name: integrateddb
    restart: unless-stopped

    # Publish DB on host port 5433
    ports:
      - "5433:5432"

    # Persist data in cim_db folder (portable) and mount init scripts and raw data
    volumes:
      - ./cim_db:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      - ./rawdata:/rawdata:ro

    # Database configuration
    environment:
      POSTGRES_DB: cim_wizard_integrated
      POSTGRES_USER: cim_wizard_user
      POSTGRES_PASSWORD: cim_wizard_password
      PGDATA: /var/lib/postgresql/data/pgdata

    # Health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

    # Network configuration
    networks:
      - cim_network

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cim_wizard_pgadmin
    restart: unless-stopped
    
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cimwizard.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    
    ports:
      - "5050:80"
    
    depends_on:
      - db
    
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    
    networks:
      - cim_network

volumes:
  pgadmin_data:
    name: cim_wizard_pgadmin_data

networks:
  cim_network:
    name: cim_wizard_network
    driver: bridge