name: webgis
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python>=3.10,<3.12
  
  # Core geospatial libraries (main requirements)
  - gdal>=3.6.0
  - geos>=3.11.0
  - proj>=9.1.0
  - shapely>=2.0.0
  - fiona>=1.9.0
  - pyproj>=3.5.0
  - rtree>=1.0.0
  
  # FastAPI and web (main requirements)
  - fastapi>=0.100.0
  - uvicorn>=0.20.0
  - python-multipart
  - python-dotenv
  
  # Data processing
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  
  # Basic utilities
  - pyyaml
  - requests
  - pip
  
  # pip dependencies (packages that work better via pip)
  - pip:
      # Database
      - sqlalchemy>=2.0.0
      - alembic>=1.10.0
      - psycopg2-binary>=2.9.0
      - geoalchemy2>=0.14.0
      - asyncpg>=0.28.0
      
      # Geospatial extensions
      - geopandas>=1.0.0
      - geojson-pydantic>=1.0.0
      - osmnx>=2.0.0
      - pyogrio>=0.10.0
      
      # FastAPI extensions
      - fastapi-pagination>=0.12.0
      - slowapi>=0.1.0
      - fastapi-utils>=0.2.0
      - pydantic>=2.5.0
      
      # HTTP and async
      - httpx>=0.25.0
      - aiofiles>=23.0.0
      
      # Development and testing
      - pytest>=7.0.0
      - pytest-asyncio>=0.21.0
      - pytest-cov>=4.0.0
      - black>=23.0.0
      - flake8>=6.0.0
      - mypy>=1.7.0
      - types-requests>=2.31.0
      - python-json-logger>=2.0.0

variables:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/webgis
  PYTHONPATH: .