name: cim_wizard_integrated
channels:
  - defaults
  - conda-forge
dependencies:
  # Python
  - python=3.10
  
  # Database
  - postgresql=15.7
  - psycopg2=2.9.7
  - sqlalchemy=2.0.23
  - alembic=1.12.1
  
  # Geospatial
  - gdal=3.6.2
  - geos=3.11.1
  - proj=9.1.1
  - shapely=2.0.1
  - geopandas=1.0.1
  - fiona=1.9.1
  - pyproj=3.5.0
  - rtree=1.4.0
  
  # FastAPI and web
  - fastapi=0.104.1
  - uvicorn=0.24.0
  - python-multipart=0.0.6
  - python-dotenv=1.0.0
  
  # Data processing
  - pandas=2.2.3
  - numpy=1.26.4
  - scipy=1.15.2
  - scikit-learn=1.6.1
  
  # HTTP client
  - requests=2.32.3
  - httpx=0.25.2
  - aiofiles=23.2.1
  
  # Utilities
  - pydantic=2.5.2
  - pyyaml=6.0.2
  - python-json-logger=2.0.7
  
  # pip dependencies
  - pip
  - pip:
      # Database extensions
      - geoalchemy2==0.14.2
      - asyncpg==0.29.0
      
      # Geospatial
      - geojson-pydantic==1.0.1
      - osmnx==2.0.0
      - pyogrio==0.11.0
      
      # FastAPI extensions
      - fastapi-pagination==0.12.13
      - slowapi==0.1.9
      - fastapi-utils==0.2.1
      
      # Testing
      - pytest==7.4.3
      - pytest-asyncio==0.21.1
      - pytest-cov==4.1.0
      - httpx==0.25.2
      
      # Development
      - black==23.11.0
      - flake8==6.1.0
      - mypy==1.7.1
      - types-requests==2.31.0.10

variables:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/cim_wizard_integrated
  PYTHONPATH: .