-- Create schema if not exists
CREATE SCHEMA IF NOT EXISTS cim_census;

-- Drop and recreate censusgeo table
DROP TABLE IF EXISTS cim_census.censusgeo CASCADE;

CREATE TABLE cim_census.censusgeo (
    id SERIAL PRIMARY KEY,
    SEZ2011 BIGINT UNIQUE,
    geometry GEOMETRY(MULTIPOLYGON, 4326),
    crs VARCHAR(100) DEFAULT 'urn:ogc:def:crs:OGC:1.3:CRS84',
    Shape_Area FLOAT,
    CODREG VARCHAR(10),
    REGIONE VARCHAR(50),
    CODPRO VARCHAR(10),
    PROVINCIA VARCHAR(50),
    CODCOM VARCHAR(10),
    COMUNE VARCHAR(50),
    PROCOM VARCHAR(10),
    NSEZ VARCHAR(10),
    ACE VARCHAR(10),
    CODLOC VARCHAR(10),
    CODASC VARCHAR(10),
    -- Population Statistics (P1-P66, P128-P140)
    P1 INTEGER, P2 INTEGER, P3 INTEGER, P4 INTEGER, P5 INTEGER,
    P6 INTEGER, P7 INTEGER, P8 INTEGER, P9 INTEGER, P10 INTEGER,
    P11 INTEGER, P12 INTEGER, P13 INTEGER, P14 INTEGER, P15 INTEGER,
    P16 INTEGER, P17 INTEGER, P18 INTEGER, P19 INTEGER, P20 INTEGER,
    P21 INTEGER, P22 INTEGER, P23 INTEGER, P24 INTEGER, P25 INTEGER,
    P26 INTEGER, P27 INTEGER, P28 INTEGER, P29 INTEGER, P30 INTEGER,
    P31 INTEGER, P32 INTEGER, P33 INTEGER, P34 INTEGER, P35 INTEGER,
    P36 INTEGER, P37 INTEGER, P38 INTEGER, P39 INTEGER, P40 INTEGER,
    P41 INTEGER, P42 INTEGER, P43 INTEGER, P44 INTEGER, P45 INTEGER,
    P46 INTEGER, P47 INTEGER, P48 INTEGER, P49 INTEGER, P50 INTEGER,
    P51 INTEGER, P52 INTEGER, P53 INTEGER, P54 INTEGER, P55 INTEGER,
    P56 INTEGER, P57 INTEGER, P58 INTEGER, P59 INTEGER, P60 INTEGER,
    P61 INTEGER, P62 INTEGER, P64 INTEGER, P65 INTEGER, P66 INTEGER,
    P128 INTEGER, P129 INTEGER, P130 INTEGER, P131 INTEGER, P132 INTEGER,
    P135 INTEGER, P136 INTEGER, P137 INTEGER, P138 INTEGER, P139 INTEGER, P140 INTEGER,
    -- Housing Statistics (ST1-ST15)
    ST1 INTEGER, ST2 INTEGER, ST3 INTEGER, ST4 INTEGER, ST5 INTEGER,
    ST6 INTEGER, ST7 INTEGER, ST8 INTEGER, ST9 INTEGER, ST10 INTEGER,
    ST11 INTEGER, ST12 INTEGER, ST13 INTEGER, ST14 INTEGER, ST15 INTEGER,
    -- Building Age Distribution (E1-E31) 
    E1 INTEGER, E2 INTEGER, E3 INTEGER, E4 INTEGER, E5 INTEGER,
    E6 INTEGER, E7 INTEGER, E8 INTEGER, E9 INTEGER, E10 INTEGER,
    E11 INTEGER, E12 INTEGER, E13 INTEGER, E14 INTEGER, E15 INTEGER,
    E16 INTEGER, E17 INTEGER, E18 INTEGER, E19 INTEGER, E20 INTEGER,
    E21 INTEGER, E22 INTEGER, E23 INTEGER, E24 INTEGER, E25 INTEGER,
    E26 INTEGER, E27 INTEGER, E28 INTEGER, E29 INTEGER, E30 INTEGER, E31 INTEGER,
    -- Building Attributes (only available columns: A2, A3, A5, A6, A7, A44, A46, A47, A48)
    A2 INTEGER, A3 INTEGER, A5 INTEGER, A6 INTEGER, A7 INTEGER,
    A44 INTEGER, A46 INTEGER, A47 INTEGER, A48 INTEGER,
    -- Family Statistics (PF1-PF9)
    PF1 INTEGER, PF2 INTEGER, PF3 INTEGER, PF4 INTEGER, PF5 INTEGER,
    PF6 INTEGER, PF7 INTEGER, PF8 INTEGER, PF9 INTEGER
);

-- Copy data from census_torino to censusgeo (using NULLIF to handle empty strings AND 'null' strings)
INSERT INTO cim_census.censusgeo (
    SEZ2011, geometry, Shape_Area, CODREG, REGIONE, CODPRO, PROVINCIA,
    CODCOM, COMUNE, PROCOM, NSEZ, ACE, CODLOC, CODASC,
    P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16, P17, P18, P19, P20,
    P21, P22, P23, P24, P25, P26, P27, P28, P29, P30, P31, P32, P33, P34, P35, P36, P37, P38, P39, P40,
    P41, P42, P43, P44, P45, P46, P47, P48, P49, P50, P51, P52, P53, P54, P55, P56, P57, P58, P59, P60,
    P61, P62, P64, P65, P66, P128, P129, P130, P131, P132, P135, P136, P137, P138, P139, P140,
    ST1, ST2, ST3, ST4, ST5, ST6, ST7, ST8, ST9, ST10, ST11, ST12, ST13, ST14, ST15,
    E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20,
    E21, E22, E23, E24, E25, E26, E27, E28, E29, E30, E31,
    A2, A3, A5, A6, A7, A44, A46, A47, A48,
    PF1, PF2, PF3, PF4, PF5, PF6, PF7, PF8, PF9
)
SELECT 
    sez2011::BIGINT, wkb_geometry, shape_area, codreg, regione, codpro, provincia,
    codcom, comune, procom, nsez, ace, codloc, codasc,
    NULLIF(NULLIF(p1, ''), 'null')::INTEGER, NULLIF(NULLIF(p2, ''), 'null')::INTEGER, NULLIF(NULLIF(p3, ''), 'null')::INTEGER, NULLIF(NULLIF(p4, ''), 'null')::INTEGER, NULLIF(NULLIF(p5, ''), 'null')::INTEGER, 
    NULLIF(NULLIF(p6, ''), 'null')::INTEGER, NULLIF(NULLIF(p7, ''), 'null')::INTEGER, NULLIF(NULLIF(p8, ''), 'null')::INTEGER, NULLIF(NULLIF(p9, ''), 'null')::INTEGER, NULLIF(NULLIF(p10, ''), 'null')::INTEGER,
    NULLIF(NULLIF(p11, ''), 'null')::INTEGER, NULLIF(NULLIF(p12, ''), 'null')::INTEGER, NULLIF(NULLIF(p13, ''), 'null')::INTEGER, NULLIF(NULLIF(p14, ''), 'null')::INTEGER, NULLIF(NULLIF(p15, ''), 'null')::INTEGER, 
    NULLIF(NULLIF(p16, ''), 'null')::INTEGER, NULLIF(NULLIF(p17, ''), 'null')::INTEGER, NULLIF(NULLIF(p18, ''), 'null')::INTEGER, NULLIF(NULLIF(p19, ''), 'null')::INTEGER, NULLIF(NULLIF(p20, ''), 'null')::INTEGER,
    NULLIF(NULLIF(p21, ''), 'null')::INTEGER, NULLIF(NULLIF(p22, ''), 'null')::INTEGER, NULLIF(NULLIF(p23, ''), 'null')::INTEGER, NULLIF(NULLIF(p24, ''), 'null')::INTEGER, NULLIF(NULLIF(p25, ''), 'null')::INTEGER, 
    NULLIF(NULLIF(p26, ''), 'null')::INTEGER, NULLIF(NULLIF(p27, ''), 'null')::INTEGER, NULLIF(NULLIF(p28, ''), 'null')::INTEGER, NULLIF(NULLIF(p29, ''), 'null')::INTEGER, NULLIF(NULLIF(p30, ''), 'null')::INTEGER,
    NULLIF(NULLIF(p31, ''), 'null')::INTEGER, NULLIF(NULLIF(p32, ''), 'null')::INTEGER, NULLIF(NULLIF(p33, ''), 'null')::INTEGER, NULLIF(NULLIF(p34, ''), 'null')::INTEGER, NULLIF(NULLIF(p35, ''), 'null')::INTEGER, 
    NULLIF(NULLIF(p36, ''), 'null')::INTEGER, NULLIF(NULLIF(p37, ''), 'null')::INTEGER, NULLIF(NULLIF(p38, ''), 'null')::INTEGER, NULLIF(NULLIF(p39, ''), 'null')::INTEGER, NULLIF(NULLIF(p40, ''), 'null')::INTEGER,
    NULLIF(NULLIF(p41, ''), 'null')::INTEGER, NULLIF(NULLIF(p42, ''), 'null')::INTEGER, NULLIF(NULLIF(p43, ''), 'null')::INTEGER, NULLIF(NULLIF(p44, ''), 'null')::INTEGER, NULLIF(NULLIF(p45, ''), 'null')::INTEGER, 
    NULLIF(NULLIF(p46, ''), 'null')::INTEGER, NULLIF(NULLIF(p47, ''), 'null')::INTEGER, NULLIF(NULLIF(p48, ''), 'null')::INTEGER, NULLIF(NULLIF(p49, ''), 'null')::INTEGER, NULLIF(NULLIF(p50, ''), 'null')::INTEGER,
    NULLIF(NULLIF(p51, ''), 'null')::INTEGER, NULLIF(NULLIF(p52, ''), 'null')::INTEGER, NULLIF(NULLIF(p53, ''), 'null')::INTEGER, NULLIF(NULLIF(p54, ''), 'null')::INTEGER, NULLIF(NULLIF(p55, ''), 'null')::INTEGER, 
    NULLIF(NULLIF(p56, ''), 'null')::INTEGER, NULLIF(NULLIF(p57, ''), 'null')::INTEGER, NULLIF(NULLIF(p58, ''), 'null')::INTEGER, NULLIF(NULLIF(p59, ''), 'null')::INTEGER, NULLIF(NULLIF(p60, ''), 'null')::INTEGER,
    NULLIF(NULLIF(p61, ''), 'null')::INTEGER, NULLIF(NULLIF(p62, ''), 'null')::INTEGER, NULLIF(NULLIF(p64, ''), 'null')::INTEGER, NULLIF(NULLIF(p65, ''), 'null')::INTEGER, NULLIF(NULLIF(p66, ''), 'null')::INTEGER, 
    NULLIF(NULLIF(p128, ''), 'null')::INTEGER, NULLIF(NULLIF(p129, ''), 'null')::INTEGER, NULLIF(NULLIF(p130, ''), 'null')::INTEGER, NULLIF(NULLIF(p131, ''), 'null')::INTEGER, NULLIF(NULLIF(p132, ''), 'null')::INTEGER,
    NULLIF(NULLIF(p135, ''), 'null')::INTEGER, NULLIF(NULLIF(p136, ''), 'null')::INTEGER, NULLIF(NULLIF(p137, ''), 'null')::INTEGER, NULLIF(NULLIF(p138, ''), 'null')::INTEGER, NULLIF(NULLIF(p139, ''), 'null')::INTEGER, NULLIF(NULLIF(p140, ''), 'null')::INTEGER,
    NULLIF(NULLIF(st1, ''), 'null')::INTEGER, NULLIF(NULLIF(st2, ''), 'null')::INTEGER, NULLIF(NULLIF(st3, ''), 'null')::INTEGER, NULLIF(NULLIF(st4, ''), 'null')::INTEGER, NULLIF(NULLIF(st5, ''), 'null')::INTEGER, 
    NULLIF(NULLIF(st6, ''), 'null')::INTEGER, NULLIF(NULLIF(st7, ''), 'null')::INTEGER, NULLIF(NULLIF(st8, ''), 'null')::INTEGER, NULLIF(NULLIF(st9, ''), 'null')::INTEGER, NULLIF(NULLIF(st10, ''), 'null')::INTEGER,
    NULLIF(NULLIF(st11, ''), 'null')::INTEGER, NULLIF(NULLIF(st12, ''), 'null')::INTEGER, NULLIF(NULLIF(st13, ''), 'null')::INTEGER, NULLIF(NULLIF(st14, ''), 'null')::INTEGER, NULLIF(NULLIF(st15, ''), 'null')::INTEGER,
    NULLIF(NULLIF(e1, ''), 'null')::INTEGER, NULLIF(NULLIF(e2, ''), 'null')::INTEGER, NULLIF(NULLIF(e3, ''), 'null')::INTEGER, NULLIF(NULLIF(e4, ''), 'null')::INTEGER, NULLIF(NULLIF(e5, ''), 'null')::INTEGER, 
    NULLIF(NULLIF(e6, ''), 'null')::INTEGER, NULLIF(NULLIF(e7, ''), 'null')::INTEGER, NULLIF(NULLIF(e8, ''), 'null')::INTEGER, NULLIF(NULLIF(e9, ''), 'null')::INTEGER, NULLIF(NULLIF(e10, ''), 'null')::INTEGER, 
    NULLIF(NULLIF(e11, ''), 'null')::INTEGER, NULLIF(NULLIF(e12, ''), 'null')::INTEGER, NULLIF(NULLIF(e13, ''), 'null')::INTEGER, NULLIF(NULLIF(e14, ''), 'null')::INTEGER, NULLIF(NULLIF(e15, ''), 'null')::INTEGER, 
    NULLIF(NULLIF(e16, ''), 'null')::INTEGER, NULLIF(NULLIF(e17, ''), 'null')::INTEGER, NULLIF(NULLIF(e18, ''), 'null')::INTEGER, NULLIF(NULLIF(e19, ''), 'null')::INTEGER, NULLIF(NULLIF(e20, ''), 'null')::INTEGER,
    NULLIF(NULLIF(e21, ''), 'null')::INTEGER, NULLIF(NULLIF(e22, ''), 'null')::INTEGER, NULLIF(NULLIF(e23, ''), 'null')::INTEGER, NULLIF(NULLIF(e24, ''), 'null')::INTEGER, NULLIF(NULLIF(e25, ''), 'null')::INTEGER, 
    NULLIF(NULLIF(e26, ''), 'null')::INTEGER, NULLIF(NULLIF(e27, ''), 'null')::INTEGER, NULLIF(NULLIF(e28, ''), 'null')::INTEGER, NULLIF(NULLIF(e29, ''), 'null')::INTEGER, NULLIF(NULLIF(e30, ''), 'null')::INTEGER, NULLIF(NULLIF(e31, ''), 'null')::INTEGER,
    NULLIF(NULLIF(a2, ''), 'null')::INTEGER, NULLIF(NULLIF(a3, ''), 'null')::INTEGER, NULLIF(NULLIF(a5, ''), 'null')::INTEGER, NULLIF(NULLIF(a6, ''), 'null')::INTEGER, NULLIF(NULLIF(a7, ''), 'null')::INTEGER,
    NULLIF(NULLIF(a44, ''), 'null')::INTEGER, NULLIF(NULLIF(a46, ''), 'null')::INTEGER, NULLIF(NULLIF(a47, ''), 'null')::INTEGER, NULLIF(NULLIF(a48, ''), 'null')::INTEGER,
    NULLIF(NULLIF(pf1, ''), 'null')::INTEGER, NULLIF(NULLIF(pf2, ''), 'null')::INTEGER, NULLIF(NULLIF(pf3, ''), 'null')::INTEGER, NULLIF(NULLIF(pf4, ''), 'null')::INTEGER, NULLIF(NULLIF(pf5, ''), 'null')::INTEGER, 
    NULLIF(NULLIF(pf6, ''), 'null')::INTEGER, NULLIF(NULLIF(pf7, ''), 'null')::INTEGER, NULLIF(NULLIF(pf8, ''), 'null')::INTEGER, NULLIF(NULLIF(pf9, ''), 'null')::INTEGER
FROM public.census_torino;

-- Create spatial index
CREATE INDEX idx_censusgeo_geometry ON cim_census.censusgeo USING GIST(geometry);
CREATE INDEX idx_censusgeo_sez2011 ON cim_census.censusgeo(SEZ2011);

-- Verify the data
SELECT COUNT(*) as total_records, 
       COUNT(DISTINCT sez2011) as unique_sez2011,
       MIN(sez2011) as min_sez,
       MAX(sez2011) as max_sez
FROM cim_census.censusgeo;